home/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from home.models import ParkingSpot
from . import views


urlpatterns = [
    # home page -- /
    url(r'^$', views.home, name='home'),

    # create account -- /signup/
    url(r'^signup/', views.signup, name='signup'),

    # search for parking spot -- /search/
    url(r'^search/', views.SearchView.as_view(), name='search'),

    # sign in page
    url(r'^signin/', views.signin, name='signin'),

    # account page
    url(r'^account/', views.UserDetail.as_view(), name='account'),

    # selling page
    url(r'^sell/', views.sell, name='sell'),

    # log out
    url(r'^log_out/', views.log_out, name='log_out'),

    # about page
    url(r'^about/', views.about, name='about'),
]

    # url(r'^signout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),

parkMi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.STATIC_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class ParkingSpot(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=25, default="")
    zipcode = models.CharField(max_length=5, default="")
    street = models.CharField(max_length=50, default="")
    city = models.CharField(max_length=15, default="")
    state = models.CharField(max_length=2, default="")
    price = models.IntegerField(default=0)
    picture = models.FileField(null=True, blank=True)
    description = models.TextField(max_length=1000, default="", blank=True)

    def get_absolute_url(self):
        return reverse('')

    def __str__(self):
        return self.title

home/forms.py
from django.contrib.auth.models import User
from .models import ParkingSpot
from django import forms


class SearchForm(forms.ModelForm):
    city = forms.CharField(max_length=20)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)

        for key in self.fields:
        	self.fields[key].widget.attrs.update({
            'class': 'form-control'
        })

      	# self.fields['first_name'].widget.attrs.update({
      	# 	'class': 'form-control mini'
      	# 	})

      	# self.fields['last_name'].widget.attrs.update({
      	# 	'class': 'form-control mini'
      	# 	})
        
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']
        help_texts = {
            'username': None,
        }


class ParkingSpotForm(forms.ModelForm):
	class Meta:
		model = ParkingSpot
		fields = ['title', 'street', 'city', 'state', 'zipcode', 'price', 'picture', 'description']

	def __init__(self, *args, **kwargs):
		super(ParkingSpotForm, self).__init__(*args, **kwargs)

		for key in self.fields:
			if key is not 'picture':
				self.fields[key].widget.attrs.update({
					'class': 'form-control'
					})



home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView
from .forms import UserForm, SearchForm, ParkingSpotForm
from .models import ParkingSpot
from django.contrib.auth.models import User
from django.utils import timezone


# need to add: bootstrap styling
class UserDetail(UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'username']
    template_name = 'home/account.html'
    success_url = '/account?success=true'
    
    def get_object(self):
        return self.request.user

    def __init__(self, *args, **kwargs):
        super(UserDetail, self).__init__(*args, **kwargs)
        for field in self.fields:
            print(field)


def about(request):
    return render(request, 'home/about.html', {})


def home(request):
    return render(request, 'home/home.html', {})


@login_required
def sell(request):
    if request.method == "POST":
        form = ParkingSpotForm(request.POST)
        if form.is_valid():
            spot = form.save(commit=False)
            spot.owner = request.user
            spot.save()

            # to do: make success page
            return HttpResponseRedirect(reverse('home'))
    else:
        form = ParkingSpotForm()

    return render(request, 'home/sell.html', {'form':form})



# figure out how to make name inputs inline
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            user = User.objects.create_user(**form.cleaned_data)
            login(request, user)
            # do stuff
            return HttpResponseRedirect(reverse(home))
    else:
        form = UserForm()

    url = reverse(home, urlconf=None, args=None, kwargs=None)
    return render(request, 'home/signup.html', {'form': form})


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        next_page = request.POST['next']
        if next_page == "":
            next_page = reverse(home)
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(next_page)
        else:
            return HttpResponse("error")
    return render(request, 'home/signin.html', {})


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse(home))


class SearchView(ListView):
    model = ParkingSpot
    template_name = 'home/search.html'

    context_object_name = 'foundspots'

    def get_queryset(self):
        print ParkingSpot.objects.filter(city__icontains=self.request.GET.get('city'))
        return ParkingSpot.objects.filter(city__icontains=self.request.GET.get('city'))

# def create(request):
#     if request.method == "POST":
#         form = QuestionChoiceForm(request.POST)
#         if form.is_valid():
#             question = form.save(commit=False)
#             question.pub_date = timezone.now()
#             question.save()
#             question.choice_set.create(choice_text=form.cleaned_data['c1'], votes=0).save()
#             question.choice_set.create(choice_text=form.cleaned_data['c2'], votes=0).save()
#             if form.cleaned_data['c3'] != "":
#                 question.choice_set.create(choice_text=form.cleaned_data['c3'], votes=0).save()
#             if form.cleaned_data['c4'] != "":
#                 question.choice_set.create(choice_text=form.cleaned_data['c4'], votes=0).save()
#             return HttpResponseRedirect(reverse('polls:index'))
#     else:
#         form = QuestionChoiceForm()
#     return render(request, 'polls/create.html', {'form':form})

"""
def search(request):
    spots = ParkingSpot.objects.all()
    city = request.GET['city']
    spots = spots.filter(city__icontains=city)
    if spots:
        response = "spots in " + city + ":<br>" + '<br>'.join([str(i) for i in spots]) + "<p><a href=\"/\">back</a></p>"
    else:
        response = "no spots found in city " + city + ", sorry :c<p><a href=\"/\">back</a></p>"
    return HttpResponse(response)

"""

### POST form syntax
# if request.method == "POST":
#     form = QuestionChoiceForm(request.POST)
#     if form.is_valid():
#         question = form.save(commit=False)
#         question.pub_date = timezone.now()
#         question.save()
#         question.choice_set.create(choice_text=form.cleaned_data['c1'], votes=0).save()
#         question.choice_set.create(choice_text=form.cleaned_data['c2'], votes=0).save()
#         if form.cleaned_data['c3'] != "":
#             question.choice_set.create(choice_text=form.cleaned_data['c3'], votes=0).save()
#         if form.cleaned_data['c4'] != "":
#             question.choice_set.create(choice_text=form.cleaned_data['c4'], votes=0).save()
#         return HttpResponseRedirect(reverse('polls:index'))
# else:
#     form = QuestionChoiceForm()
# return render(request, 'polls/create.html', {'form':form})

home/templates/home/about.html
{% extends 'home/base.html' %}

{% block content %}



{% endblock %}

home/templates/home/account.html
{% extends 'home/base.html' %}

{% block content %}


 	<div>	<!-- temporarily unclassed -->
	 	<h2>Your Account</h2>

	 	{% if request.GET.success %}
	 		<p><span class="med">Your changes have been saved.</span></p>
	 	{% endif %}
	 	
	  	<form method="POST" class="sign edit">
		{% csrf_token %}

			<p>Email: <strong> {{ object.email }} </strong></p>

		    <div class="form-group">

		  		{{ form.as_p }}

		  		<button class="btn btn-default submit" type="submit">Update</button>
		  	</div>
	  	</form>

	  	<h2>Your Spots</h2>
	  	<!-- add more details, and detail/edit view for spot -->
	  	{% for spot in object.parkingspot_set.all %}
	  		<p> {{ spot.title }} </p>
	  	{% endfor %}
  </div>

{% endblock %}

home/templates/home/base.html
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'home/style.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <title>ParkMi</title>
</head>

<body>


<!-- NAVIGATION -->
  <nav class="navbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home'%}" class="active">ParkMi</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

          <li><a href="{% url 'sell' %}">Sell</a></li>

        {% if user.is_authenticated %}

          <li><a href="{% url 'account' %}">Account</a></li>
          <li><a href="{% url 'log_out' %}">Log out</a>

        {% else %}
          <li><a href="{% url 'signin' %}">Sign In</a></li>
          <li><a href="{% url 'signup' %}">Sign up</a></li>

        {% endif %}

      </ul>
  </nav>


<!-- main content (will be vertically & horizontally centered w flexbox)
 --> 
  <div class="main">
    {% block content %}
    {% endblock %}
  </div>


<!-- footer (temp?) -->
  <div class="footer">
    <span class="l"><a href="{% url 'about' %}">
      Learn More
    </a></span>
    <span class="l"><a href="">
      Contact Us
    </a></span>
    <span class="r">
      &copy; 2017 ParkMi
    </span>
  </div>


</body>

</html>

home/templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}

<!-- HOMEPAGE -->

      <!-- Title and Search Bar -->
      <div class="home">
        <span class="name anim">ParkMi</span>
        <br>
        <span class="caption">Find parking anywhere, anytime.</span>
        <br>

        <form action="{% url 'search' %}" method="GET" id="locate">
        <span>Where are you headed?<br></span>
          <div class="input-group">
             <input type="text" class="form-control" placeholder="Your destination!" name="city" required>
             <span class="input-group-btn">
                  <button class="btn btn-default" type="submit">Go!</button>
             </span>
          </div>
        </form>
      </div>

{% endblock %}

home/templates/home/search.html
{% extends 'home/base.html' %}

{% block content %}

	<div style="text-align:left">	<!-- temporarily unclassed -->
		<h2>Spots in {{ request.GET.city|title }}</h2>
		{% for spot in foundspots %}
			<strong>{{ spot.title }}</strong><br>
			Address:<br>
			{{ spot.street }}<br>
			{{ spot.city }}, {{spot.state}} {{spot.zipcode}}
		{% empty %}
		Sorry, no spots found.
		{% endfor %}
		<form action="{% url 'home' %}">
    		<button class="btn btn-default submit" type="submit" style="margin-top:20px;">Back</button>
		</form>
	</div>

{% endblock %}

home/templates/home/sell.html
{% extends 'home/base.html' %}

{% block content %}

	<div style="margin-top:50px;margin-bottom:50px;">	<!-- temporarily unclassed -->
		<h2>Sell a Spot</h2>
		<form action="{% url 'sell' %}" method="POST" class="sign">
		{% csrf_token %}
			<div class="form-group">
				{{ form.as_p }}
				<button class="btn btn-default submit" type="submit">Submit</button>
			</div>

	</div>

{% endblock %}

home/templates/home/signin.html
{% extends 'home/base.html' %}

{% block content %}

<!-- SIGN IN -->
	<div style="height:400px;">	<!-- temporarily unclassed -->

		<h2>Sign in</h2>
		<form action="{% url 'signin' %}" method="POST" class="sign">
		{% csrf_token %}

		{% if request.GET.next %}
			<p>Please sign in first.</p>
		{% endif %}
		<div class="form-group">
			<p><label for="username">Username:</label>
			<input type="text" class="form-control" placeholder="Your username" name="username" id="username" required></p>

			<p><label for="password">Password:</label>
			<input type="password" class="form-control" placeholder="Your password" name="password" id="password" required></p>

			<input type="hidden" name="next" value="{{request.GET.next}}">

			<button class="btn btn-default submit" type="submit">Sign in</button>
		</div>
		</form>

	</div>
{% endblock %}

home/templates/home/signup.html
{% extends 'home/base.html' %}

{% block content %}

<!-- SIGN IN -->

	<div>	<!-- temporarily unclassed -->
		<h2>Create an Account</h2>
		<form action="{% url 'signin' %}" method="POST" class="sign">
		{% csrf_token %}
			<div class="form-group">
				{{ form.as_p }}
				<button class="btn btn-default submit" type="submit">Sign in</button>
			</div>

	</div>
{% endblock %}